<?php

namespace ContainerH6xUDC1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XXhxS9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xXhxS_9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xXhxS_9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\AdminPropertyController::edit' => ['privates', '.service_locator.xmtwBk4', 'get_ServiceLocator_XmtwBk4Service', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.ml6kUnq', 'get_ServiceLocator_Ml6kUnqService', true],
            'App\\Controller\\PropertyController::show' => ['privates', '.service_locator.xmtwBk4', 'get_ServiceLocator_XmtwBk4Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\AdminPropertyController:edit' => ['privates', '.service_locator.xmtwBk4', 'get_ServiceLocator_XmtwBk4Service', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.ml6kUnq', 'get_ServiceLocator_Ml6kUnqService', true],
            'App\\Controller\\PropertyController:show' => ['privates', '.service_locator.xmtwBk4', 'get_ServiceLocator_XmtwBk4Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\AdminPropertyController::edit' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\PropertyController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\AdminPropertyController:edit' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\PropertyController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
