<?php

namespace ContainerYRx22rc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropertyFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PropertyFormType' shared autowired service.
     *
     * @return \App\Form\PropertyFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PropertyFormType.php';

        return $container->privates['App\\Form\\PropertyFormType'] = new \App\Form\PropertyFormType();
    }
}
