<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYRx22rc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYRx22rc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYRx22rc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYRx22rc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYRx22rc\App_KernelDevDebugContainer([
    'container.build_hash' => 'YRx22rc',
    'container.build_id' => '17e0cb3c',
    'container.build_time' => 1675344577,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYRx22rc');
